import { test, expect } from "@playwright/test";
import { createGuestWorkspace, prepareIsolatedRussianGuest, waitForApp } from "./guest-test-helpers.js";

test("split stock, transfer, cancellation, location filters and destination purchases survive reload", async ({ page }) => {
  await prepareIsolatedRussianGuest(page);
  const { item } = await createGuestWorkspace(page, { layoutName: "Поход", containerName: "Еда", itemName: "Каша", quantity: "6" });
  await item.locator(".item-title-hitarea").click();
  await page.locator("#itemStockQuantity").fill("4");
  await page.locator("#itemStockLocationsBtn").click();
  const dialog = page.locator("#stockLocationsDialog");
  const names = dialog.locator("[data-stock-location-name]");
  const quantities = dialog.locator("[data-stock-location-quantity]");
  await names.first().fill("Дом");
  await dialog.locator("[data-stock-add]").click();
  await names.nth(1).fill("Дача");
  await dialog.locator("[data-stock-move-count]").fill("2");
  await dialog.locator("[data-stock-move]").click();
  await expect(quantities.first()).toHaveValue("2");
  await expect(quantities.nth(1)).toHaveValue("2");
  await expect(dialog.locator("[data-stock-total]")).toHaveText("4");
  await dialog.locator("[data-stock-save]").click();
  await expect(dialog).not.toBeVisible();
  await expect(page.locator("#itemStockLocationsSummary")).toHaveText("Дом: 2 · Дача: 2");
  await expect(page.locator("#itemStockQuantity")).toHaveAttribute("readonly", "");
  expect((await page.locator("#itemStockQuantity").boundingBox()).width).toBeGreaterThanOrEqual(60);
  await expect(page.getByRole("checkbox", { name: "Требует заряда", exact: true })).toHaveCount(1);
  await page.screenshot({ path: "test-results/stock-locations-editor.png", fullPage: true });
  await page.locator("#saveItemBtn").click();
  await expect(item.locator(".preparation-buy")).toHaveText("Докупить: 2 шт.");
  await page.reload();
  await waitForApp(page);
  await page.locator('.tab[data-view="items"]').click();
  for (const place of ["Дом", "Дача"]) {
    await page.locator("#locationFilter").selectOption(place);
    await expect(page.locator("#itemsView [data-list-item-id]")).toHaveCount(1);
  }
  await page.locator("[data-stock-locations]").click();
  await quantities.first().fill("-1");
  await dialog.getByRole("button", { name: "Отмена", exact: true }).click();
  await page.locator("[data-stock-locations]").click();
  await expect(quantities.first()).toHaveValue("2");
  await dialog.locator("[data-stock-from]").selectOption("1");
  await dialog.locator("[data-stock-to]").selectOption("0");
  await dialog.locator("[data-stock-move]").click();
  await expect(quantities.first()).toHaveValue("3");
  await expect(quantities.nth(1)).toHaveValue("1");
  await page.setViewportSize({ width: 390, height: 844 });
  await page.screenshot({ path: "test-results/stock-locations-mobile.png" });
  expect(await dialog.evaluate((element) => element.scrollWidth <= element.clientWidth)).toBe(true);
  await dialog.locator("[data-stock-save]").click();
  await page.locator("#locationFilter").selectOption("");
  await page.locator('.tab[data-view="packing"]').click();
  await page.locator('[data-preparation-action="buy"]').click();
  await page.locator("[data-purchase-location]").selectOption("Дача");
  await page.locator("[data-purchase-item] button").click();
  await expect(page.locator("#preparationDialog")).toContainText("Всего хватает");
  await page.locator("[data-preparation-close]").click();
  await page.reload();
  await waitForApp(page);
  await page.locator('.tab[data-view="items"]').click();
  await page.locator("[data-stock-locations]").click();
  await expect(quantities.first()).toHaveValue("3");
  await expect(quantities.nth(1)).toHaveValue("3");
  await expect(dialog.locator("[data-stock-total]")).toHaveText("6");
});
