import test from "node:test";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { createPersonalJournalStorage } from "../../src/storage/personal-journal-storage.js";
import { createPersonalSaveOutbox } from "../../src/sync/personal-save-outbox.js";
import { createPersonalSaveRecovery } from "../../src/sync/personal-save-recovery.js";

const binding = { environment: "bike-packing-experiment", actorId: "test-actor", listId: "test-list", scopeKey: "id:test-actor" };
const prefix = `bike-packing-personal-save-v1:${encodeURIComponent(JSON.stringify(binding))}:`;
const byteSize = values => [...values].reduce((sum, [key, raw]) => sum + 2 * (key.length + raw.length), 0);
const clone = value => structuredClone(value);
const quotaError = () => new DOMException("synthetic test quota", "QuotaExceededError");

async function fixture() {
  const values = new Map(), states = new Map(), locks = new Map();
  const f = { values, states, quota: Infinity };
  f.legacy = { get length() { return values.size; }, key: index => [...values.keys()][index] ?? null,
    getItem: key => values.get(key) ?? null, removeItem: key => values.delete(key),
    setItem(key, raw) {
      if (byteSize(new Map([...values, [key, raw]])) > f.quota) throw quotaError();
      values.set(key, raw);
    } };
  f.locks = { request(name, callback) {
    const task = (locks.get(name) || Promise.resolve()).then(callback);
    locks.set(name, task.catch(() => {})); return task;
  } };
  f.repository = {
    async read(owner) { return clone(states.get(JSON.stringify(owner)) || { revision: 0, entries: [] }); },
    async commit(owner, { expectedRevision, puts, deletes }) {
      await f.beforeCommit?.();
      const previous = states.get(JSON.stringify(owner)) || { revision: 0, entries: [] };
      assert.equal(previous.revision, expectedRevision);
      const identity = row => `${row.namespace}:${row.key}`;
      const entries = new Map(previous.entries.map(row => [identity(row), row]));
      for (const row of puts) { assert.equal(entries.has(identity(row)), false); entries.set(identity(row), clone(row)); }
      for (const row of deletes) { assert.equal(row.namespace, "snapshot"); entries.delete(identity(row)); }
      states.set(JSON.stringify(owner), { revision: expectedRevision + 1, entries: [...entries.values()] });
      return { revision: expectedRevision + 1 };
    }
  };
  // Synthetic data: representative payload size, no exported user content.
  f.payload = name => ({ items: { item: { id: "item", name, note: "x".repeat(394500) } },
    containers: {}, layouts: { layout: { id: "layout", name: "Synthetic packing list" } } });
  f.input = (name, revision = 9) => {
    const payload = f.payload(name);
    return { snapshot: { ...clone(payload), activeLayoutId: "layout", localUi: "packing" },
      body: { baseStateRevision: revision, payload } };
  };
  f.make = storage => createPersonalSaveOutbox({ storage, ...binding });
  f.open = () => createPersonalJournalStorage(f);
  const initial = f.make(f.legacy);
  const first = f.input("initial", 5);
  await initial.adoptRemoteBaseline({ snapshot: first.snapshot, payload: first.body.payload, stateRevision: 5 });
  for (let generation = 1; generation <= 4; generation++) {
    const input = f.input(`confirmed-${generation}`, 4 + generation);
    const record = await initial.capture(input);
    initial.markApplied({ operationId: record.action.operationId, stateRevision: 5 + generation });
    await initial.adoptRemoteBaseline({ snapshot: input.snapshot, payload: input.body.payload, stateRevision: 5 + generation });
    await initial.compact();
  }
  // Match the old singleton-anchor grammar using a certificate generated by
  // the native outbox, not a hand-built imitation of the protocol.
  const checkpointKey = [...values.keys()].find(key => key.startsWith(`${prefix}checkpoint:`));
  values.set(`${prefix}anchor`, values.get(checkpointKey)); values.delete(checkpointKey);
  const head = initial.recover();
  assert.equal(head.action.generation, 4);
  assert.equal(values.size, 3);
  const size = byteSize(values);
  assert.ok(size > 2.2 * 1024 * 1024 && size < 2.4 * 1024 * 1024, `representative queue size: ${size}`);
  // Other site data leaves insufficient room for one more full legacy record.
  values.set("other-site-data", "r".repeat(1_000_000));
  f.quota = 5 * 1024 * 1024;
  f.original = [...values]; f.head = head;
  return f;
}

test("representative 2.26 MiB queue captures offline rename durably, reloads, and confirms with async compaction", async () => {
  const f = await fixture(), input = f.input("renamed offline");
  assert.throws(() => f.make(f.legacy).capture(input), { code: "quota" });
  assert.deepEqual([...f.values], f.original, "failed legacy capture retains the complete queue");
  const storage = await f.open(), outbox = f.make(storage);
  let release;
  f.beforeCommit = () => new Promise(resolve => { release = resolve; });
  const saving = outbox.capture(input);
  while (!release) await new Promise(resolve => setImmediate(resolve));
  assert.equal(outbox.recover().action.operationId, f.head.action.operationId);
  assert.equal(outbox.hasPending(), false, "in-flight bytes are not an already captured action");
  release(); const saved = await saving;
  f.beforeCommit = null;
  await storage.flush();
  assert.equal(outbox.hasPending(), true);
  assert.equal(saved.action.generation, 5);
  assert.deepEqual(saved.snapshot, input.snapshot);
  assert.equal(f.values.get("other-site-data"), "r".repeat(1_000_000));
  assert.ok([...f.values].filter(([key]) => key.startsWith(prefix)).every(([, raw]) => raw.length < 1024));
  const coldStorage = await f.open(), cold = f.make(coldStorage);
  assert.deepEqual(cold.recover(), saved);
  assert.deepEqual(cold.recoverSnapshot(), input.snapshot);
  assert.equal(cold.confirmedBase(), null, "local durability alone is not server confirmation");
  cold.markApplied({ operationId: saved.action.operationId, stateRevision: 10 });
  await cold.adoptRemoteBaseline({ snapshot: input.snapshot, payload: input.body.payload, stateRevision: 10 });
  await cold.compact();
  await coldStorage.flush();
  const confirmed = f.make(await f.open());
  assert.equal(confirmed.hasPending(), false);
  assert.deepEqual(confirmed.confirmedBase().payload, input.body.payload);
  assert.equal(confirmed.confirmedBase().stateRevision, 10);
  assert.deepEqual(confirmed.recoverSnapshot(), input.snapshot);
  // Normal repeated edits retain only their current body/checkpoint. Small
  // applied markers remaining inline must not suppress full-payload cleanup.
  const currentStorage = await f.open(), current = f.make(currentStorage);
  const originalRows = [...f.states.values()][0].entries.filter(row => row.namespace === "journal").length;
  for (let revision = 11; revision <= 13; revision++) {
    const next = f.input(`follow-up-${revision}`, revision - 1), record = await current.capture(next);
    current.markApplied({ operationId: record.action.operationId, stateRevision: revision });
    await current.adoptRemoteBaseline({ snapshot: next.snapshot, payload: next.body.payload, stateRevision: revision });
    await current.compact(); await currentStorage.flush();
    const rows = [...f.states.values()][0].entries;
    assert.equal(rows.filter(row => row.namespace === "snapshot").length, 2, "only current action and checkpoint remain");
    assert.equal(rows.filter(row => row.namespace === "journal").length, originalRows, "fixed migration copies do not grow per edit");
  }
});

test("competing asynchronous captures preserve the observed predecessor and reject the losing stale editor", async () => {
  const f = await fixture(), storage = await f.open();
  const first = f.make(storage), second = f.make(storage);
  const results = await Promise.allSettled([first.capture(f.input("first draft")), second.capture(f.input("second draft"))]);
  assert.equal(results[0].status, "fulfilled");
  assert.equal(results[1].status, "rejected");
  assert.equal(results[1].reason.code, "stale-tab");
  const cold = f.make(await f.open()), head = cold.recover();
  assert.equal(head.action.operationId, results[0].value.action.operationId);
  assert.equal(head.action.body.payload.items.item.name, "first draft");
  assert.equal(cold.list().length, 2);
  assert.equal(cold.hasPending(), true);
  assert.equal(cold.confirmedBase(), null);
});

test("failed durable capture exports the memory draft and exact original queue without confirming or publishing it", async () => {
  const f = await fixture(), storage = await f.open();
  const recovery = createPersonalSaveRecovery();
  const outbox = recovery.outbox(() => f.make(storage), binding.scopeKey);
  const before = [...f.values], input = f.input("draft retained after quota"), operationId = randomUUID();
  f.beforeCommit = () => { throw quotaError(); };
  await assert.rejects(outbox.capture({ ...input, operationId }), { code: "quota" });
  assert.deepEqual([...f.values], before);
  assert.equal(storage.getItem(prefix + operationId), null);
  const copy = recovery.recoveryCopy(storage);
  assert.equal(copy.reasonCode, "quota"); assert.equal(copy.memoryDraftAvailable, true);
  assert.deepEqual(copy.unconfirmedMemoryDraft, input.snapshot);
  assert.deepEqual(copy.journalEntries.map(({ key, value }) => [key, value]), f.original.filter(([key]) => key.startsWith(prefix)));
  const cold = f.make(await f.open());
  assert.equal(cold.recover().action.operationId, f.head.action.operationId);
  assert.equal(cold.recoverSnapshot().items.item.name, "confirmed-4");
  assert.equal(cold.confirmedBase().stateRevision, 9);
  assert.equal(cold.list().some(record => record.action.operationId === operationId), false);
});

test("failed asynchronous baseline checkpoint retains the previous confirmed baseline and all source bytes", async () => {
  const f = await fixture(), storage = await f.open(), outbox = f.make(storage);
  const before = [...f.values], remote = f.input("newer remote", 10);
  f.beforeCommit = () => { throw quotaError(); };
  await assert.rejects(outbox.adoptRemoteBaseline({ snapshot: remote.snapshot, payload: remote.body.payload, stateRevision: 10 }),
    error => error.isPersonalSaveBlocked === true);
  assert.deepEqual([...f.values], before);
  assert.equal(f.make(storage).confirmedBase().stateRevision, 9);
  assert.equal(f.make(storage).recoverSnapshot().items.item.name, "confirmed-4");
  assert.ok([...f.states.values()][0].entries.some(row => row.raw === f.original.find(([key]) => key.endsWith(":anchor"))[1]));
});
